<a href="https://colab.research.google.com/github/Ibratbey/Data-Science/blob/main/8_26_NumPy_kutubxonasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np
print(np.version)
print(np.show_config)

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>
<function show at 0x7cbb92d318a0>


#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [2]:
arr_num = np.array([1,2,3,4,5,6])

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




`💡Ishora` np.zeros

In [3]:
arr_zeros = np.zeros(9)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [4]:
arr = np.ones((3,5))
arr_size = arr.itemsize
print(f"arrayning xotira hajmi : {arr_size}")

arrayning xotira hajmi : 8


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [6]:
arr = np.array([0,0,0,0,0,1,0,0,0,0,0,0])
arr.size

12

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [7]:
arr_7 = np.arange(20,60)
arr_7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [8]:
arr = np.arange(10)
arr_reverse = arr[::-1]
arr_reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [15]:
arr = np.arange(12,21).reshape(3,3)
arr

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [17]:
arr = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [20]:
arr_rand = np.random.random(8).reshape(2,2,2)
arr_rand

array([[[0.76601597, 0.67434706],
        [0.23998867, 0.41728752]],

       [[0.8995759 , 0.93557037],
        [0.96552822, 0.44024635]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [22]:
arr = np.random.random(81).reshape(9,9)
minn = np.min(arr)
maxx = np.max(arr)
print(arr)
print(f"Arrayning eng kichik qiymati {minn}")
print(f"Arrayning eng katta qiymati {maxx}")

[[0.23557731 0.17870725 0.26115868 0.98602701 0.03989227 0.53475472
  0.04012812 0.01983213 0.43117806]
 [0.52420756 0.60286084 0.31921398 0.88544163 0.9080356  0.45314607
  0.04726156 0.73091831 0.14162259]
 [0.83957575 0.00959807 0.91713878 0.91921785 0.30478941 0.41453564
  0.61991457 0.49169745 0.15013088]
 [0.57502208 0.63831654 0.26975027 0.60897155 0.88230561 0.68390825
  0.97571944 0.88436947 0.2172802 ]
 [0.53335073 0.50281079 0.62836018 0.50019969 0.47247798 0.75071491
  0.00700282 0.10004977 0.13846416]
 [0.26002778 0.2921334  0.56500847 0.42531887 0.2280545  0.46896045
  0.33581117 0.84531912 0.33383217]
 [0.2138606  0.20390312 0.60953757 0.94073374 0.27250021 0.89617985
  0.79632864 0.29127483 0.66255907]
 [0.89738712 0.32707658 0.13485659 0.37885739 0.99934342 0.32570225
  0.14740725 0.19073169 0.94816658]
 [0.13795481 0.37634948 0.05873681 0.30674116 0.31755158 0.89292539
  0.22986335 0.99383183 0.06769595]]
Arrayning eng kichik qiymati 0.00700282095710425
Arrayning eng 

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [23]:
0 * np.nan

nan

In [24]:
np.nan == np.nan

False

In [25]:
np.inf > np.nan

False

In [26]:
np.nan - np.nan

nan

In [27]:
np.nan in set([np.nan])

True

In [33]:
0.7 == 7 * 0.1

False

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [38]:
arr1 = np.ones(shape = (6,3))
arr2 = np.ones((3,4))
print(np.dot(arr1, arr2))

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
print(sum(range(5),-1))

9


In [41]:
from numpy import *
print(sum(range(5),-1))

10


Demak birinchi holatda pythondagi sum() ishlatildi va keyingida numpydagi sum ishlatib 2- argument axisni bildirdi va u yig'indiga qo'shilmadi

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [45]:
a = np.array([1,2])
b = np.array([4,5])
print(f"a > b : {a > b}")
print(f"a >= b : {a >= b}")
print(f"a<b : {a < b}")
print(f"a<=b : {a <= b}")

a > b : [False False]
a >= b : [False False]
a<b : [ True  True]
a<=b : [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [51]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipython-input-3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [52]:
arr1 = np.arange(2,10)
arr2 = np.arange(8,16)
np.intersect1d(arr1, arr2)

array([8, 9])

#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [63]:
arr = np.random.uniform(-5,10, 5)
print(arr)
musbat_arr = arr[arr>0]
musbat_arr
res_mod = musbat_arr - (musbat_arr % 1)
print("\n1) modulo (%) usuli:\n", res_mod)

res_trunc = np.trunc(musbat_arr)
print("\n2) np.trunc():\n", res_trunc)

res_astype = musbat_arr.astype(int)
print("\n3) astype(int):\n", res_astype)

res_floor = np.floor(musbat_arr)
print("\n4) np.floor():\n", res_floor)

[-2.99969899 -3.44888711  8.96322975  2.59166784 -1.19860694]

1) modulo (%) usuli:
 [8. 2.]

2) np.trunc():
 [8. 2.]

3) astype(int):
 [8 2]

4) np.floor():
 [8. 2.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [73]:
arr = np.arange(3).repeat(3).reshape(3, 3)
arr = arr.T
print(arr)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [77]:
arr = np.random.randint(-6,34, 10)
print(f"asl arr : {arr}")
print(f"tartiblangan arr: {np.sort(arr)}")

asl arr : [-3 23 31  3  3 32 26 24 19 12]
tartiblangan arr: [-3  3  3 12 19 23 24 26 31 32]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`