<a href="https://colab.research.google.com/github/Ibratbey/Data-Science/blob/main/8_26_NumPy_kutubxonasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np
print(np.version)
print(np.show_config)

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>
<function show at 0x7d4d2f32d8a0>


#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [2]:
arr_num = np.array([1,2,3,4,5,6])

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




`💡Ishora` np.zeros

In [3]:
arr_zeros = np.zeros(9)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [4]:
arr = np.ones((3,5))
arr_size = arr.itemsize
print(f"arrayning xotira hajmi : {arr_size}")

arrayning xotira hajmi : 8


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [6]:
arr = np.array([0,0,0,0,0,1,0,0,0,0,0,0])
arr.size

12

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [7]:
arr_7 = np.arange(20,60)
arr_7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [8]:
arr = np.arange(10)
arr_reverse = arr[::-1]
arr_reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [9]:
arr = np.arange(12,21).reshape(3,3)
arr

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [10]:
arr = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [11]:
arr_rand = np.random.random(8).reshape(2,2,2)
arr_rand

array([[[0.53987769, 0.71032914],
        [0.85395372, 0.3950356 ]],

       [[0.02131377, 0.0879573 ],
        [0.99141591, 0.70910695]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [12]:
arr = np.random.random(81).reshape(9,9)
minn = np.min(arr)
maxx = np.max(arr)
print(arr)
print(f"Arrayning eng kichik qiymati {minn}")
print(f"Arrayning eng katta qiymati {maxx}")

[[4.97145690e-01 9.12453820e-01 7.22115096e-01 6.61605181e-01
  6.98982064e-01 4.82518128e-01 7.43675721e-01 2.71683131e-04
  1.55143895e-01]
 [8.31239679e-01 2.97634318e-01 9.35328652e-01 4.05043726e-01
  4.99314892e-01 9.36065905e-01 3.26271226e-01 1.21926714e-02
  1.29450785e-01]
 [3.81442451e-01 5.11797826e-01 9.66523540e-01 4.04029150e-01
  5.98070976e-01 4.80877522e-02 2.30670821e-01 4.02510214e-01
  4.97575871e-01]
 [8.41111894e-01 6.45165876e-02 9.58061537e-01 1.34204683e-01
  8.65339457e-01 1.29913111e-01 4.48272989e-01 3.11886547e-01
  1.51713374e-01]
 [2.10127964e-01 4.65122497e-01 1.62668636e-01 9.87754566e-01
  6.14766755e-01 6.15273000e-01 4.34805198e-01 7.94755545e-01
  9.68231567e-01]
 [4.32434935e-01 3.31105805e-01 9.08832118e-02 5.98937618e-01
  7.64936120e-01 5.29167922e-01 7.62776641e-01 1.78756701e-01
  9.28607578e-01]
 [5.78485740e-01 4.76822400e-01 2.23750422e-01 1.34598673e-01
  9.88309027e-01 7.12540874e-01 4.74585992e-01 8.19837381e-01
  8.71541665e-01]
 [4.50

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [13]:
0 * np.nan

nan

In [14]:
np.nan == np.nan

False

In [15]:
np.inf > np.nan

False

In [16]:
np.nan - np.nan

nan

In [17]:
np.nan in set([np.nan])

True

In [18]:
0.7 == 7 * 0.1

False

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [19]:
arr1 = np.ones(shape = (6,3))
arr2 = np.ones((3,4))
print(np.dot(arr1, arr2))

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [20]:
print(sum(range(5),-1))

9


In [21]:
from numpy import *
print(sum(range(5),-1))

10


Demak birinchi holatda pythondagi sum() ishlatildi va keyingida numpydagi sum ishlatib 2- argument axisni bildirdi va u yig'indiga qo'shilmadi

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [22]:
a = np.array([1,2])
b = np.array([4,5])
print(f"a > b : {a > b}")
print(f"a >= b : {a >= b}")
print(f"a<b : {a < b}")
print(f"a<=b : {a <= b}")

a > b : [False False]
a >= b : [False False]
a<b : [ True  True]
a<=b : [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [23]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipython-input-3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [24]:
arr1 = np.arange(2,10)
arr2 = np.arange(8,16)
np.intersect1d(arr1, arr2)

array([8, 9])

#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [25]:
arr = np.random.uniform(-5,10, 5)
print(arr)
musbat_arr = arr[arr>0]
musbat_arr
res_mod = musbat_arr - (musbat_arr % 1)
print("\n1) modulo (%) usuli:\n", res_mod)

res_trunc = np.trunc(musbat_arr)
print("\n2) np.trunc():\n", res_trunc)

res_astype = musbat_arr.astype(int)
print("\n3) astype(int):\n", res_astype)

res_floor = np.floor(musbat_arr)
print("\n4) np.floor():\n", res_floor)

[ 1.10155429  2.69805725 -3.73437312  8.20492819 -1.3552123 ]

1) modulo (%) usuli:
 [1. 2. 8.]

2) np.trunc():
 [1. 2. 8.]

3) astype(int):
 [1 2 8]

4) np.floor():
 [1. 2. 8.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [26]:
arr = np.arange(3).repeat(3).reshape(3, 3)
arr = arr.T
print(arr)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [27]:
arr = np.random.randint(-6,34, 10)
print(f"asl arr : {arr}")
print(f"tartiblangan arr: {np.sort(arr)}")

asl arr : [30 20 -4 31 12 31 15  8  4 11]
tartiblangan arr: [-4  4  8 11 12 15 20 30 31 31]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [31]:
arr1 = np.random.rand(5)
arr2 = np.random.rand(5)
print(f"arr1 : {arr1} \narr2 : {arr2}")
print(f"arr1 == arr2(np.allclose)  : {np.allclose(arr1,arr2)}")
print(f"arr1 == arr2 (np.array_equal) : {np.array_equal(arr1, arr2)}")

arr1 : [0.7214084  0.65473021 0.0239179  0.95075867 0.13607632] 
arr2 : [0.39205845 0.68986806 0.09346179 0.38965539 0.47114967]
arr1 == arr2(np.allclose)  : False
arr1 == arr2 (np.array_equal) : False


#### 23. Oʻlchamlari 6x3 va 3x4 matritsa tuzing va ularni oʻzaro koʻpaytiring.


`💡Ishora` np.dot or np.ones

In [35]:
arr1 = np.ones((6,3))
arr2 = np.ones((3,4))
print(f"arr1 * arr2 = \n{np.dot(arr1, arr2)}")

arr1 * arr2 = 
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [42]:
arr = np.random.rand(5)
print(f"arr = {arr}")
maxx_index = np.argmax(arr)
print(maxx_index)
arr[maxx_index] = 0
print(arr)

arr = [0.80385882 0.97579712 0.3135277  0.42860209 0.02289249]
1
[0.80385882 0.         0.3135277  0.42860209 0.02289249]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [64]:
bugun = np.datetime64('today')
kecha = bugun - np.timedelta64(1,"D")
erta = bugun + np.timedelta64(1,"D")
print(f"kecha : {kecha}")
print(f"bugun : {bugun}")
print("erta : ", erta)

kecha : 2025-11-20
bugun : 2025-11-21
erta :  2025-11-22


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [66]:
dates = np.arange(
    '2016-01-01',
    '2016-02-01',
    dtype='datetime64[D]'
)
dates

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [67]:
arr = np.random.uniform(-5,10, 5)
print(arr)
musbat_arr = arr[arr>0]
musbat_arr
res_mod = musbat_arr - (musbat_arr % 1)
print("\n1) modulo (%) usuli:\n", res_mod)

res_trunc = np.trunc(musbat_arr)
print("\n2) np.trunc():\n", res_trunc)

res_astype = musbat_arr.astype(int)
print("\n3) astype(int):\n", res_astype)

res_floor = np.floor(musbat_arr)
print("\n4) np.floor():\n", res_floor)

[ 4.25392921  6.83159289 -1.18842588 -1.7937195   8.46787043]

1) modulo (%) usuli:
 [4. 6. 8.]

2) np.trunc():
 [4. 6. 8.]

3) astype(int):
 [4 6 8]

4) np.floor():
 [4. 6. 8.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [70]:
arr1 = np.arange(5)
arr2 = np.arange(5,10)
print(f"arr1 elementlari yig'indisi :  {np.add.reduce(arr1)}")
print(f"arr2 elementlari yig'indisi :  {np.add.reduce(arr2)}")

arr1 elementlari yig'indisi :  10
arr2 elementlari yig'indisi :  35


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [76]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.zeros(arr.size * 4 - 3, dtype=int)
new_arr[::4] = arr
print(new_arr)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [78]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
from numpy.lib.stride_tricks import as_strided
# Window o'lchami va step
window_size = 4

# as_strided yordamida b yaratish
b = as_strided(
    a,
    shape=(len(a) - window_size + 1, window_size),
    strides=(a.strides[0], a.strides[0])
)

print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`