<a href="https://colab.research.google.com/github/Ibratbey/Data-Science/blob/main/Indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
dat = ['Ibratbek','Asadulloh', 'Shahzod','Asad', 'Shuhrat','Bekzod','Davron'] # Kvartiradagi talabalar ismlari
arr = np.array(dat)
arr

array(['Ibratbek', 'Asadulloh', 'Shahzod', 'Asad', 'Shuhrat', 'Bekzod',
       'Davron'], dtype='<U9')

In [5]:
arr1 = arr[:2] # Data Science ga qiziqadigan talabalar
arr1

array(['Ibratbek', 'Asadulloh'], dtype='<U9')

In [6]:
arr2 = arr[1:5] # Ingliz tilidan o'quv kursiga boradigan talabalar
arr2

array(['Asadulloh', 'Shahzod', 'Asad', 'Shuhrat'], dtype='<U9')

In [7]:
arr2[1] = ''
arr2

array(['Asadulloh', '', 'Asad', 'Shuhrat'], dtype='<U9')

In [8]:
arr2 = np.delete(arr2,1) #Ingliz tilidan o'quv kursiga boradigan talabalar ro'yhatidan Shahzodni chiqarib tashlaymiz
arr2

array(['Asadulloh', 'Asad', 'Shuhrat'], dtype='<U9')

In [9]:
arr # asosiy array

array(['Ibratbek', 'Asadulloh', '', 'Asad', 'Shuhrat', 'Bekzod', 'Davron'],
      dtype='<U9')

In [10]:
arr3 = arr[:2]# arrayning dastlabki 2 ta elementini kesib olamiz
arr3

array(['Ibratbek', 'Asadulloh'], dtype='<U9')

In [12]:
arr3[0] = "Ibratulloh " #arr3 ni 0- indeksdagi qiymatini o'zgartiramiz
arr3

array(['Ibratullo', 'Asadulloh'], dtype='<U9')

In [13]:
arr3[0]

'Ibratullo'

In [17]:
print(arr3)

['Ibratullo' 'Asadulloh']


In [18]:
print(arr)# arr massivimizni ro'yhatga chiqarib ko'ramiz

['Ibratullo' 'Asadulloh' '' 'Asad' 'Shuhrat' 'Bekzod' 'Davron']


In [22]:
arr[2] = 'Shahzod'

## Demak biror arrayni boshqa arraydan elementlarini kesib olib yaratsak va yangi array ustida amallar bajarsak, bu elementlari kesib olingan arrayga ham tasir qilar ekan. Buni oldini olish uchun boshqa usulni ko'rib chiqamiz

# copy usuli

In [23]:
arr4 = arr[1:5].copy() # arr arrayidan 1-dan 5- indeksgacha nusxa olamiz
arr4

array(['Asadulloh', 'Shahzod', 'Shahzod', 'Shuhrat'], dtype='<U9')

In [24]:
#Asadullohni arr4 massividan chiqarib tashlaymiz
arr4 = np.delete(arr4,0)
arr4

array(['Shahzod', 'Shahzod', 'Shuhrat'], dtype='<U9')

## Keling endi arr arrayimizni tekshirib ko'ramiz, Asadulloh arr arrayimizdan ham o'chib ketganmikan

In [25]:
print(arr)

['Ibratullo' 'Asadulloh' 'Shahzod' 'Shahzod' 'Shuhrat' 'Bekzod' 'Davron']


## Demak bu safar arr array o'zgarmay qoldi

# Ikki o'lchamli (2d array) massivlarda indeks va kesib olish

In [26]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2d array 9 ta elementdan iborat
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2d.ndim

2

## **size metodi**

In [29]:
# arr2d massividagi elementlari sonini aniqlaymiz
arr2d.size

9

2 o'ljamli massivning bir nechta elementlarini kesib olish

In [35]:
qism_arr2d = arr2d[:2,1:]  # 
qism_arr2d

array([[2, 3],
       [5, 6]])

In [36]:
qism_arr2d.shape

(2, 2)

In [37]:
qism_arr2d = arr2d[1:,:]
qism_arr2d

array([[4, 5, 6],
       [7, 8, 9]])

In [38]:
qism_arr2d.shape

(2, 3)

3 o'lchamli massivlarda indekslash va kesib olish

In [41]:
arr3d = np.array([
                  [[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]],
                  [[13,14,15],[16,17,18]]
                  ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [46]:
print(arr3d.ndim)  #arr3d ni o'lchami
print(arr3d.shape) #Shakli
arr3d.size  #elementlari soni

3
(3, 2, 3)


18

In [48]:
qism_arr3d = arr3d[0].copy()
qism_arr3d

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
qism_arr3d = arr3d[2][:,:2].copy()
qism_arr3d

array([[13, 14],
       [16, 17]])

In [53]:
qism_arr3d = arr3d[:2].copy()
qism_arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# **Bugungi mavzu qisqacha shundan iborat**